Feature lw 1 refactoring of routes
itechart-warehouse/trucking pull request #1
Opened 2022-05-19 10:18 UTC by helmy-er

2022-05-19 11:37 UTC, NDragneelL9 approved these changes

2022-05-19 12:02 UTC, alllpim approved these changes

2022-05-19 13:32 UTC, NDragneelL9 approved these changes

2022-05-20 08:07 UTC, Lonely-fr approved these changes

2022-05-20 10:12 UTC, kel-ln requested changes

2022-05-20 10:12 UTC, kel-ln commented on config/routes.rb
> +  resources :goods_owner, only: :index
resources :goods_owner, only: :index, path: "goodsowners"

2022-05-20 10:12 UTC, kel-ln commented on config/routes.rb
> -  resources :roles, only: :index
контроллер не используется ?

2022-05-20 10:12 UTC, kel-ln commented on config/routes.rb
> -  resources :trucks
контроллер не используется?

2022-05-20 10:13 UTC, kel-ln commented
придерживайтесь единого стиля ведения веток 
{bug|feature|hotfix}/{TASK-ID}-{short-task-description}

2022-05-20 10:36 UTC, helmy-er commented on config/routes.rb
> -  resources :trucks
yes ,it's useless controllers

2022-05-20 13:11 UTC, merged