Feature lw 7 pagination
itechart-warehouse/trucking pull request #10
Opened 2022-05-20 10:50 UTC by helmy-er

2022-05-24 14:53 UTC, Laranto-spb approved these changes

2022-05-24 16:30 UTC, NDragneelL9 requested changes
update

2022-05-24 16:30 UTC, NDragneelL9 commented on app/controllers/consignments_controller.rb
> -    render json: @consignment
why did u remove this line?

2022-05-25 09:52 UTC, kel-ln requested changes
1. название ветки 
2. добавить тесты на измененные контроллеры

2022-05-25 09:52 UTC, kel-ln commented on app/controllers/companies_controller.rb
> +  @@companies_per_page = 5
очень сложно, ты же этот класс не наследуешь, да и зачем в каждом классе отдельно выставлять значение пагинации, в случае если в будущем понадобятся изменения нужно будет проходиться по каждому классу и вручную менять

можно сделать один метод или одну статическую переменную в общем классе. как тебе более кажется правильным

DEFAULT_PAGE_SIZE = 5

def  default_page_size
    params[:per_page] || 5
end

2022-05-25 09:52 UTC, kel-ln commented on app/controllers/companies_controller.rb
> +
почему разделено на 2 метода ? пагинацию нужно добавить в экшен index, а то сейчас у тебя 2 экшена делают одно и тоже 
и желательно общее количество элементов на странице тоже получать

2022-05-25 09:52 UTC, kel-ln commented on app/controllers/waybills_controller.rb
> +  @@WAYBILLS_PER_PAGE = 5
если ты хочешь объявить переменную класса не используй заглавные буквы

2022-05-25 09:52 UTC, kel-ln commented on config/routes.rb
> +    get '/:page/(:perPage)',to: 'pages#page'
page и perPage можно передавать как не обязательные параметры в роуте index

2022-05-25 10:40 UTC, kel-ln requested changes

2022-05-25 10:40 UTC, kel-ln commented on app/controllers/companies_controller.rb
> +    page = params.fetch(:page, 0).to_i * @@companies_per_page.to_i
значения nil, 0 и 1  - это всегда первая страница 
у тебя получается система отсчета начинается с 0

2022-05-31 05:30 UTC, kel-ln requested changes

2022-05-31 05:30 UTC, kel-ln commented on app/controllers/api/v1/consignments_controller.rb
> +        page = params.fetch(:page, 0).to_i * default_page_size
отсчет страниц идет с 1   
первая страница это записи с 0 по 5
вторая страница записи с 6 по 10
... 
у тебя сейчас сдвинуты страницы на 1
когда приходит запрос на получение данных 2 страницы ты по факту возвращаешь данные 3

2022-05-31 05:30 UTC, kel-ln commented on app/controllers/api/v1/consignments_controller.rb
>          end
с массивами можно проще
consignment_api_columns  = Consignment.attribute_names - excluded_columns

2022-05-31 05:30 UTC, kel-ln commented on app/controllers/companies_controller.rb
> +    render json: companies if params[:page]
а если значение nil  у тебя вообще ответа не будет ?

2022-05-31 05:30 UTC, kel-ln commented on config/routes.rb
> +    get '/(:page)/(:perPage)',to: 'pages#users_index',as: "users"
параметры page и perPage ну должны быть обязательными 
что то такое должно быьт  ?page=&per_page=

2022-05-31 08:41 UTC, helmy-er commented on app/controllers/companies_controller.rb
> +    render json: companies if params[:page]
yes, it's depend on our front-end logic .We send this global vars to props from react

2022-06-01 12:24 UTC, kel-ln requested changes

2022-06-01 12:24 UTC, kel-ln commented on app/controllers/application_controller.rb
> +  end
надо это в один файл вынести, а потом подключить в application_controller и в api_controller

2022-06-01 12:24 UTC, kel-ln commented on app/controllers/companies_controller.rb
> +                  Company.accessible_by(current_ability).offset(offset_page).limit(default_page_size)
может  offset(offset_page).limit(default_page_size) вынести в метод который будет работать с коллекцией ?
def paginate_collection(collection)
   collection.offset(offset_page).limit(default_page_size)
end


```suggestion
                  paginate_collection(Company.accessible_by(current_ability))
```

2022-06-02 12:34 UTC, kel-ln requested changes

2022-06-02 12:34 UTC, kel-ln commented on app/controllers/api/v1/api_controller.rb
> +      end
у тебя эти методы подключены в include Concerns::Paginatable
их можно удалить

2022-06-02 12:34 UTC, kel-ln commented on app/controllers/api/v1/consignments_controller.rb
> +        ), consignments_count: Consignment.select(consignment_api_columns).length }
надо бы чтоб общее количество элементов, тоже считалось в paginate_collection
можешь сделать чтоб метод возвращал 2 переменные, одна это коллекция а вторая это мета информация с общем количеством элементов, текущей страницей, и общим количеством страниц

2022-06-06 11:49 UTC, kel-ln requested changes

2022-06-06 11:49 UTC, kel-ln commented on app/controllers/api/v1/consignments_controller.rb
> +                       consignments_count: consignments_data[1][:total_count] }
```suggestion
        consignments, meta = paginate_collection(Consignment.select(consignment_api_columns))
        render json: { consignments: consignments.to_json(include: included_params),
                                consignments_count: meta.total_count }
```

старайтесь чтоб код выглядел проще

2022-06-06 11:49 UTC, kel-ln commented on app/controllers/api/v1/drivers_controller.rb
> +        drivers_data = paginate_collection(User.select(drivers_api_columns).where(role: Role.find_by(role_name: 'driver')))
```suggestion
        drivers = User.select(drivers_api_columns)
                                .joins(:roles)
                                .where(roles: { role_name: 'driver' } )
        drivers_data = paginate_collection(drivers)
```

2022-06-06 11:49 UTC, kel-ln commented on app/controllers/concerns/paginatable.rb
> +      collection.length / default_page_size
```suggestion
      (collection.length.to_f / default_page_size).ceil
```
если у тебя записей будет меньше чем количество записей на странице
12 / 5  = 2  страницы, а должно быть 3

2022-06-06 11:49 UTC, kel-ln commented on app/models/trucking_audit.rb
>    end
надо сделать rebase к основной ветке эти изменения должны быть там

2022-06-06 12:26 UTC, helmy-er commented on app/models/trucking_audit.rb
>    end
это изменения рубокопа

2022-06-07 07:57 UTC, kel-ln approved these changes

2022-06-07 09:57 UTC, Lonely-fr approved these changes

2022-06-07 12:58 UTC, merged