Origin/feature/lw 10 controller refactor
itechart-warehouse/trucking pull request #11
Opened 2022-05-20 11:33 UTC by Lonely-fr

https://trello.com/c/1REb9vBF

2022-05-24 12:42 UTC, alllpim approved these changes

2022-05-24 14:49 UTC, Laranto-spb commented on app/controllers/users_controller.rb
> +    @serialized_users = ActiveModelSerializers::SerializableResource.new(users).to_json
Maybe separate this to method  for DRY?

2022-05-24 15:30 UTC, NDragneelL9 approved these changes

2022-05-24 15:30 UTC, NDragneelL9 commented on entrypoints/docker-entrypoint.sh
> +exec "$@"
probably u dont need to upload files with these type of changes like here and in Dockerfile

2022-05-24 20:39 UTC, Lonely-fr commented on config/routes.rb
>    end
Controller refactoring is not route refactoring. Optimization was carried out on the basis of past commits.

2022-05-25 08:35 UTC, helmy-er approved these changes

2022-05-25 10:29 UTC, kel-ln requested changes
1. название ветки не должно быть ключевого слова "origin"
2. добавить тесты на  этот контроллер

2022-05-25 10:29 UTC, kel-ln commented on app/controllers/users_controller.rb
> +    User.find(params.require(:id)).destroy
это прямое обращение к переменной можно просто params[:id]

2022-05-25 10:29 UTC, kel-ln commented on config/routes.rb
>    end
тк ресурс users отдали под devise, для избежания путаницы лучше поменять название ресурса или путь к нему( например members или employees )

2022-05-25 10:36 UTC, MonkeyKingBar-bit approved these changes

2022-05-25 16:41 UTC, NDragneelL9 commented on app/controllers/users_controller.rb
> +    @serialized_users = ActiveModelSerializers::SerializableResource.new(users).to_json
в данном случае, @serialized_companies использует на create user form, где администратор выбирает для какой компании он создает пользователя.

2022-05-25 16:42 UTC, NDragneelL9 commented on config/routes.rb
>    end
Не обратил на это внимания, извиняюсь

2022-05-31 05:32 UTC, kel-ln commented
коменты с прошлого CR не исправлены

2024-11-06 20:40 UTC, closed without merging