Feature/lw 11 searching backend
itechart-warehouse/trucking pull request #15
Opened 2022-06-01 12:13 UTC by helmy-er

2022-06-01 12:31 UTC, kel-ln requested changes

2022-06-08 13:35 UTC, NDragneelL9 approved these changes

2022-06-09 17:26 UTC, kel-ln requested changes

2022-06-09 17:26 UTC, kel-ln commented on app/controllers/api/v1/consignments_controller.rb
> +        end
```suggestion
        query = Consignment.select(consignment_api_columns)
        query = query.search(params[:search]) unless params[:query].blank?
        consignments, meta = paginate_collection(query)
        render json: { consignments: consignments.to_json(include: included_params),
                         consignments_count: meta[:total_count] }
```

2022-06-09 17:26 UTC, kel-ln commented on app/controllers/api/v1/drivers_controller.rb
> +        end
как в примере выше

2022-06-09 17:26 UTC, kel-ln commented on app/controllers/api/v1/trucks_controller.rb
> +        end
как в примере выше

2022-06-09 17:26 UTC, kel-ln commented on app/models/company.rb
> +  scope :search, ->(search) { where("name ilike '#{search}%'") }
название должно быть говорящим, а то пока в модель не зайдешь не поймешь что именно будет искать
к примеру  scope :by_name, ->(q) {}

2022-06-09 17:26 UTC, kel-ln commented on app/models/consignment.rb
> +
не очень хорошая реализация у тебя идет split в контекстном поиске получается сравнение с null ?
если уже вообще по другому сделать нельзя то хотя бы на подзапросы разбей или выноси работу с параметров в контроллер

```suggestion
  scope :search, lambda { |search|
                    seria, number = search.split
                   query = "consignment_seria ILIKE '#{seria}%'"
                    query += " and consignment_number::text  ILIKE '#{number}%'" if !number.blank?
                    where(query)
                 }

```

2022-06-09 17:26 UTC, kel-ln commented on app/views/devise/shared/_links.html.erb
> +  <%= link_to "Didn't receive unlock instructions?", user_unlock_path(resource_name), class: 'share-links' %><br />
исправления не связанные с задачей нужно делать в отдельных ПР чтоб все могли из скачать

2022-06-13 13:09 UTC, kel-ln approved these changes

2022-06-15 12:12 UTC, Lonely-fr approved these changes

2022-06-16 09:32 UTC, MonkeyKingBar-bit approved these changes

2022-06-16 10:27 UTC, alllpim approved these changes

2022-06-16 12:12 UTC, Laranto-spb approved these changes

2022-06-20 08:06 UTC, closed without merging