feature/lw-19-sidekiq. Install sidekiq
itechart-warehouse/trucking pull request #17
Opened 2022-06-06 14:18 UTC by NDragneelL9

Added new docker configuration, so dont forget to rebuild container

2022-06-07 08:15 UTC, kel-ln approved these changes
нужно вынести namespace из url redis
редис используется для разных целей  url будет всегда один а namespace разные

2022-06-07 08:15 UTC, kel-ln commented on config/initializers/sidekiq.rb
> +end
```suggestion
REDIS_DEFAULT_URL = 'redis://localhost:6379/'
REDIS_DEFAULT_NAMESPACE = '1'

Sidekiq.configure_server do |config|
  config.redis = { url: ENV.fetch('REDIS_URL', REDIS_DEFAULT_URL),
                             namespace:  ENV.fetch('REDIS_NAMESPACE', REDIS_DEFAULT_NAMESPACE) }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV.fetch('REDIS_URL', REDIS_DEFAULT_URL),
                             namespace:  ENV.fetch('REDIS_NAMESPACE', REDIS_DEFAULT_NAMESPACE) }
end
```

2022-06-08 11:06 UTC, helmy-er approved these changes

2022-06-09 17:30 UTC, kel-ln requested changes

2022-06-09 17:30 UTC, kel-ln commented on config/routes.rb
> +  end
к единому стилю надо привести авторизацию( как на втором проекте через basicauth )

2022-06-10 09:47 UTC, NDragneelL9 commented on config/routes.rb
> +  end
Сделал

2022-06-10 18:32 UTC, kel-ln approved these changes

2022-06-13 12:16 UTC, merged