Feature/lw 25. Send birthday email
itechart-warehouse/trucking pull request #23
Opened 2022-06-17 07:22 UTC by MonkeyKingBar-bit

2022-06-21 11:07 UTC, NDragneelL9 approved these changes
Возможно стоит добавить базовые тесты, что все нужные классы отрабатывают

2022-06-21 11:07 UTC, NDragneelL9 commented on app/controllers/pages_controller.rb
> +
missclick?

2022-06-21 11:07 UTC, NDragneelL9 commented on app/helpers/birthday_mailer_helper.rb
> +end
автоматически создался? думаю пока не стоит пустые хелперы держать

2022-06-21 11:07 UTC, NDragneelL9 commented on app/jobs/users_birthday_job.rb
> +  queue_as :default
```suggestion
  queue_as :mailers
```

2022-06-21 11:07 UTC, NDragneelL9 commented on app/jobs/users_birthday_job.rb
> +    # end
думаю закоменченные строки можно уже убрать в этом файле

2022-06-21 11:07 UTC, NDragneelL9 commented on spec/helpers/birthday_mailer_helper_spec.rb
> +end
если хелпер не нужен, то и тест для него можно удалить

2022-06-22 11:27 UTC, kel-ln requested changes

2022-06-22 11:27 UTC, kel-ln commented on app/jobs/users_birthday_job.rb
> +      BirthdayMailer.birthday_email(user&.email, recipient_name(user))
```suggestion
      BirthdayMailer.birthday_email(user.email, user.full_name).deliver
```
поле email будет всегда у пользователя, тут не нужен блок try
recipient_name - где у тебя этот метод обьявлен ?  надо добавить метод для объекта и вызывать для пользователя

2022-06-22 11:27 UTC, kel-ln commented on app/mailers/birthday_mailer.rb
> +  end
у класса BirthdayMailer разве объявлены атрибуты? почему self ?
метод в любом случае вернет значение его не нужно присваивать переменной, либо переменную нужно использовать, а не присваивать новой переменной

2022-06-22 11:27 UTC, kel-ln commented on app/mailers/birthday_mailer.rb
> +    @user_name = recipient_name
у тебя тут приходит параметр recipient_name и есть метод  с таким же название что в данном интерпретатор выберет? , это путает, почему бы не использовать названия отражающие суть

2022-06-22 11:27 UTC, kel-ln commented on app/views/birthday_mailer/birthday_email.html.erb
> +</html>
можно взять любой красивый шаблон
например с этого ресурса 
https://stripo.email/ru/templates/

2022-06-22 11:27 UTC, kel-ln commented on config/sidekiq.yml
> +    cron: '0 * 9-10 * * 1-5'   # Runs from Monday to Friday every day at 9 - 10 a.m.
в записи явно что то не то проверить можно тут https://crontab.guru/
сервис должен срабатывать каждый день, почему ограничение на 5 дней в неделю ?
как пример каждый день в 9 часов утра 
что тут должно произойти не понимаю

2022-06-22 11:27 UTC, kel-ln commented on spec/jobs/users_birthday_job_spec.rb
> +end
для чего все эти пустые тесты ?

2022-06-22 11:27 UTC, kel-ln commented on test/mailers/previews/birthday_email_preview.rb
> +end
что тут происходит ?

2022-06-23 07:08 UTC, MonkeyKingBar-bit commented on app/jobs/users_birthday_job.rb
> +      BirthdayMailer.birthday_email(user&.email, recipient_name(user))
Этот метод находится в  app->mailers->birthday_mailer.rb. Туда передаётся юзер

2022-06-23 10:59 UTC, kel-ln requested changes

2022-06-23 10:59 UTC, kel-ln commented on app/jobs/users_birthday_job.rb
> +      BirthdayMailer.birthday_email(user&.email, recipient_name(user))
путь не явный перенеси в модель

2022-06-23 10:59 UTC, kel-ln commented on app/jobs/birthday_mailer_job.rb
> +      BirthdayMailer.birthday_email(user.email, recipient_name(user)).deliver
метод recipient_name нужно либо вынести в модель User
либо написать в этом же классе

2022-06-23 10:59 UTC, kel-ln commented on app/mailers/birthday_mailer.rb
> +  end
убрать этот метод

2022-06-24 06:42 UTC, kel-ln approved these changes

2022-06-24 06:42 UTC, kel-ln commented on app/jobs/birthday_mailer_job.rb
> +    "#{user.first_name} #{user.middle_name} #{user.second_name}" if user
в каких случая пользователя может не быть ?

2022-06-24 11:31 UTC, helmy-er approved these changes

2022-06-26 23:16 UTC, NDragneelL9 approved these changes

2022-06-26 23:16 UTC, NDragneelL9 commented on spec/helpers/birthday_mailer_helper_spec.rb
> +    assert_equal "You have birthday email from trucking.app.reset@gmail.com", email.subject
probably we should use ENV variable here instead of direct email

2022-06-28 18:56 UTC, alllpim approved these changes

2022-06-29 13:07 UTC, merged