Feature/l-41-countries
itechart-warehouse/trucking pull request #26
Opened 2022-06-22 10:55 UTC by helmy-er

2022-06-22 12:51 UTC, kel-ln requested changes

2022-06-22 12:51 UTC, kel-ln commented on spec/factories/cities.rb
> +    sequence(:name) { |i| "city_#{i}"}
https://github.com/faker-ruby/faker

2022-06-22 12:51 UTC, kel-ln commented on db/seeds.rb
> +                            { name: 'Brighton & Hove' },])
это города Польши ?

2022-06-22 12:51 UTC, kel-ln commented on db/migrate/20220620101256_create_cities.rb
> +      t.integer :country_id
id страны тоже не может быть пустым

2022-06-22 12:51 UTC, kel-ln commented on db/migrate/20220620094539_create_countries.rb
> +      t.string :name, null: false
нужен индекс на уникальность названия страны

2022-06-22 12:51 UTC, kel-ln commented on config/routes.rb
> +  end
можно завернуть в namespace :settings

2022-06-22 12:51 UTC, kel-ln commented on app/models/country.rb
> +  has_many :city
```suggestion
  has_many :cities
```

2022-06-22 12:51 UTC, kel-ln commented on app/controllers/countries_controller.rb
> +    render json: { countries: @countries, total_count: @total_count } if params[:page].present?
почему не через сериализатор ?
на фронт нет необходимости отправлять все данные обьекта

2022-06-22 12:51 UTC, kel-ln commented on app/controllers/countries_controller.rb
> +    country = Country.find(params[:id])
можно вынести в отдельный метод 

before_action :find_country, only: [:show, :update, :destroy]

private
  def find_country
    @ country = Country.find(params[:id])
  end

2022-06-22 12:51 UTC, kel-ln commented on app/controllers/countries_controller.rb
> +    answer(country) { country.update(name: country_params[:name]) }
```suggestion
    answer(country) { country.update(country_params) }
```

2022-06-22 12:51 UTC, kel-ln commented on app/controllers/cities_controller.rb
> +    cities, meta = paginate_collection(Country.find(params[:country_id]).city)
вынести  поиск страны и поиск города в private методы

2022-06-22 12:53 UTC, NDragneelL9 commented on app/javascript/api/clientAPI.ts
> +export const CityUrl = 'cities';
```suggestion
export const CityUrl = '/cities';
```

2022-06-22 12:53 UTC, NDragneelL9 commented on spec/requests/cities_spec.rb
> +  let(:user) { create(:user, role_id: 6) }
```suggestion
  let(:user) { create(:user_sysAdmin) }
```
Если возникает ошибка с созданием юзера, то эт наверн из-за того, что нужно добавить поле confimed_at в фактории юзера. Пример в таске L-42-measurement-units

2022-06-23 08:58 UTC, helmy-er commented on app/controllers/countries_controller.rb
> +    render json: { countries: @countries, total_count: @total_count } if params[:page].present?
просто там всего 2 поля : id name и оба используются на фронте

2022-06-23 11:06 UTC, kel-ln approved these changes

2022-06-23 11:06 UTC, kel-ln commented on app/controllers/settings/countries_controller.rb
> +  end
этот метод можно вынести в общий класс

2022-06-23 11:06 UTC, kel-ln commented on app/controllers/settings/cities_controller.rb
> +  before_action :find_country, only: %i[index create]
```suggestion
  before_action :find_country
```

2022-06-23 11:06 UTC, kel-ln commented on app/controllers/settings/cities_controller.rb
> +    @city = City.find(params[:id])
```suggestion
    @city = @country.cities.find_by(id: params[:id])
```

2022-06-23 11:06 UTC, kel-ln commented on db/seeds.rb
> +                            { name: 'Gdańsk' },])
```suggestion
Country.find_by(name: 'Poland').cities.create([{ name: 'Warsaw ' },
                            { name: 'Krakow' },
                            { name: 'Zakopane' },
                            { name: 'Gdańsk' }])
```
использовать last не самый надежный вариант

2022-06-24 09:33 UTC, MonkeyKingBar-bit requested changes
U need add search panel & delete unused files

2022-06-24 09:33 UTC, MonkeyKingBar-bit commented on app/views/settings/countries/index.html.erb
> +    <%=react_component('countries',{
The title of component must be start from uppercase letter

2022-06-24 09:33 UTC, MonkeyKingBar-bit commented on app/javascript/components/countries.tsx
> +  const { countries, total_count } = props;
U need use camelcase for this "total_count"

2022-06-24 09:33 UTC, MonkeyKingBar-bit commented on app/javascript/components/countries.tsx
> +import CompanyTable from './Company/CompanyTable';
U need delete unused components

2022-06-24 09:33 UTC, MonkeyKingBar-bit commented on app/javascript/components/countries/table.tsx
> +                    <StyledTableCell><CircularProgress color="primary" /></StyledTableCell>
It doesn't work
![image](https://user-images.githubusercontent.com/60444425/175505189-f8c71d39-5cf6-4d6b-83c5-39e8de38942a.png)

2022-06-24 09:33 UTC, MonkeyKingBar-bit commented on app/javascript/components/city/table.tsx
> +                      <StyledTableCell><CircularProgress color="primary" /></StyledTableCell>
It doesn't work
![image](https://user-images.githubusercontent.com/60444425/175505349-3af1ea06-a672-47de-98b5-9f2826469cdb.png)

2022-06-24 09:33 UTC, MonkeyKingBar-bit commented on app/javascript/components/countries.tsx
> +            Create Company
U need to create Country!

2022-06-24 09:33 UTC, MonkeyKingBar-bit commented on app/javascript/components/countries/table.tsx
> +  const [citiesCount, setCitiesCount] = React.useState<number>();
U need add initial value (e.g., 0), because u have an error in pagination
![image](https://user-images.githubusercontent.com/60444425/175506099-6285693f-0846-4840-9ed2-6cc324201b7f.png)

2022-06-24 09:33 UTC, MonkeyKingBar-bit commented on app/javascript/components/countries/createCountry.tsx
> +      <Dialog
U can delete "div, because here enough to use only Dialog, how root

2022-06-24 10:30 UTC, NDragneelL9 approved these changes

2022-06-28 06:48 UTC, MonkeyKingBar-bit approved these changes

2022-06-28 08:43 UTC, alllpim approved these changes

2022-06-28 09:25 UTC, closed without merging