Feature/l 45 localization
itechart-warehouse/trucking pull request #28
Opened 2022-06-27 12:19 UTC by helmy-er

2022-06-28 10:27 UTC, kel-ln requested changes

2022-06-28 10:27 UTC, kel-ln commented on app/controllers/application_controller.rb
> +  end
тебе нужно поменять значение локали

```suggestion
  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.locale = locale
  end
```

2022-06-28 10:27 UTC, kel-ln commented on app/controllers/application_controller.rb
> +  around_action :switch_locale
```suggestion
  before_action :switch_locale
```

2022-06-28 10:27 UTC, kel-ln commented on config/application.rb
> +    I18n.default_locale = :en
в initialize перенеси

2022-06-28 10:27 UTC, kel-ln commented on config/routes.rb
почему в этом файле добавился сдвиг ?

2022-06-28 11:00 UTC, helmy-er commented on config/routes.rb
прошёлся рубокоп по роутам

2022-06-28 11:10 UTC, kel-ln commented on config/routes.rb
для  рубокопа поставь пожалуйста  сдвиг 1 таб = 2 пробела

2022-06-28 11:47 UTC, NDragneelL9 approved these changes

2022-06-28 18:55 UTC, alllpim approved these changes

2022-06-29 11:15 UTC, kel-ln approved these changes

2022-06-30 10:29 UTC, closed without merging