feature/LW-8 Display user actions
itechart-warehouse/trucking pull request #8
Opened 2022-05-19 15:40 UTC by MonkeyKingBar-bit

… with sorting

2022-06-09 16:09 UTC, kel-ln requested changes

2022-06-09 16:09 UTC, kel-ln commented on Gemfile
> +gem 'i18n'
это лишнее он встроен в rails

2022-06-09 16:09 UTC, kel-ln commented on app/controllers/trucking_audit_controller.rb
> +    end
```suggestion
    statistics =  TruckingAudit.where.not(user_id: nil)
                               .alphabetical_sort
    statistics = statistics.search_name(params[:name]) if params[:name].present?
    statistics = statistics.search_action(params[:actions]) if params[:actions].present?
    if params[:start_date].present? && params[:end_date].present?
      statistics = statistics.search_date(params[:start_date], params[:end_date])
    end
    statistics, meta = paginate_collection(statistics)
```
более удобно читается

2022-06-09 16:09 UTC, kel-ln commented on app/models/trucking_audit.rb
> +  scope :alphabetical_sort, lambda {
```suggestion
  scope :alphabetical_sort, -> {
```
используйте короткую запись

2022-06-09 16:09 UTC, kel-ln commented on app/serializers/trucking_audit_serializer.rb
> +    object.company_id&.name
```suggestion
    object.company&.name
```
company_id  это параметр

2022-06-09 16:09 UTC, kel-ln commented on config/routes.rb
> +  resources  :trucking_audit, only: :index, path: '/statistics'
надо было контроллер сразу назвать statistics

2022-06-09 16:09 UTC, kel-ln commented on app/serializers/trucking_audit_serializer.rb
> +  attributes :id, :user_id, :username, :company, :data, :action, :changes, :type
user_id как то на фронте используется ?

2022-06-09 19:07 UTC, kel-ln requested changes

2022-06-09 19:07 UTC, kel-ln commented on app/controllers/statistics_controller.rb
> +end
этот контроллер используется ?

2022-06-09 19:07 UTC, kel-ln commented on app/models/trucking_audit.rb
> +  }
```suggestion
  scope :search_date, lambda { |start_date, end_date|
    start_date = start_date.to_date.beginning_of_day
    end_date = end_date.to_date.end_of_day
    where('created_at between ? and ?', start_date, end_date)
  }
```

2022-06-10 09:46 UTC, NDragneelL9 approved these changes

2022-06-10 09:46 UTC, NDragneelL9 commented on app/views/trucking_audit/index.html.erb
> +      statisticsCount: @statistics_count,
Если ты кидаешь запрос на получение статистики, тебе не нужно кидать данные через пропсы

2022-06-10 23:17 UTC, MonkeyKingBar-bit commented on app/serializers/trucking_audit_serializer.rb
> +  attributes :id, :user_id, :username, :company, :data, :action, :changes, :type
да

2022-06-13 08:10 UTC, helmy-er approved these changes

2022-06-13 12:54 UTC, kel-ln requested changes

2022-06-13 12:54 UTC, kel-ln commented on app/models/statistics.rb
> +class Statistics < Audited::Audit
не совсем понял а зачем название модели изменено ?

2022-06-13 12:54 UTC, kel-ln commented on app/serializers/statistics_serializer.rb
> +    object.company_id&.name
у company_id не может быть метода это атрибут 
```suggestion
    object.company&.name
```

2022-06-13 12:54 UTC, kel-ln commented on app/serializers/statistics_serializer.rb
> +  attributes :id, :user_id, :username, :company, :data, :action, :changes, :type
для чего user_id нужен на фронте ?
наверно data лучше поменять на date более понятнее будет

2022-06-13 12:54 UTC, kel-ln commented on config/routes.rb
> +  resources :statistics, only: :index, path: '/statistics'
путь прописывать нет необходимости, он одинаковый с ресурсом

2022-06-13 16:25 UTC, MonkeyKingBar-bit commented on app/serializers/statistics_serializer.rb
> +    object.company_id&.name
оно так не работает!!!
![image](https://user-images.githubusercontent.com/60444425/173400070-2e7c13fa-9d2b-4c4b-8924-a68f8c425ac6.png)
![image](https://user-images.githubusercontent.com/60444425/173400088-c9ba77ef-fbc0-43d2-a201-c7081e391045.png)
![image](https://user-images.githubusercontent.com/60444425/173400139-cc7af3ce-ef23-4446-84bf-891dd8f74d2f.png)

2022-06-14 11:49 UTC, kel-ln commented on app/serializers/statistics_serializer.rb
> +    object.company_id&.name
нужно belongs_to :company прописать в модели

2022-06-15 00:17 UTC, Lonely-fr approved these changes

2022-06-16 10:26 UTC, alllpim approved these changes

2022-06-16 11:11 UTC, kel-ln approved these changes

2022-06-21 11:10 UTC, merged